### ISSUE TITLE
Is upload request supported

### ISSUE THREAD

**Issue by m0s30** [assetnote/nowafpls#2]
Is upload request supported
![image](https://github.com/assetnote/nowafpls/assets/54650671/e22afea7-35f4-4d7f-85f1-0a76291a646b)

**Comment by infosec-au** [comment]
Multipart is not supported yet, but I'd be happy to accept a PR 😄 
At the moment only URL Encoded, XML and JSON are supported.

**Comment by infosec-au** [comment]
This is now supported!
